spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        default_schema: junit
    hibernate:
      ddl-auto: update
server:
  port: 2525